from PySide6.QtCore import QObject
from PySide6.QtGui import QAction, QKeySequence
from PySide6.QtWidgets import QMenu, QMenuBar

from app.utils.system_info import SystemInfo


class MenuBar(QObject):
    def __init__(self, menu_bar: QMenuBar) -> None:
        super().__init__()

        self.menu_bar = menu_bar

        # Menu bars are different on macOS
        if SystemInfo().operating_system == SystemInfo.OperatingSystem.MACOS:
            self._do_menu_bar_macos()
        else:
            self._do_menu_bar_non_macos()

    def _do_menu_bar_macos(self) -> None:
        # Application menu (macOS only)
        self.app_menu = self.menu_bar.addMenu(
            "应用程序名称"
        )  # This title is ignored on macOS
        self.check_for_updates_action = QAction("检查更新…", self)
        self.check_for_updates_action.setMenuRole(
            QAction.MenuRole.ApplicationSpecificRole
        )
        self.app_menu.addAction(self.check_for_updates_action)
        self.check_for_updates_on_startup_action = QAction(
            "启动时检查更新", self
        )
        self.check_for_updates_on_startup_action.setCheckable(True)
        self.check_for_updates_on_startup_action.setMenuRole(
            QAction.MenuRole.ApplicationSpecificRole
        )
        self.app_menu.addAction(self.check_for_updates_on_startup_action)
        separator = QAction(self)
        separator.setSeparator(True)
        separator.setMenuRole(QAction.MenuRole.ApplicationSpecificRole)
        self.app_menu.addAction(separator)
        self.settings_action = QAction("设置…", self)
        self.settings_action.setMenuRole(QAction.MenuRole.ApplicationSpecificRole)
        self.settings_action.setShortcut(QKeySequence("Ctrl+,"))
        self.app_menu.addAction(self.settings_action)
        self.app_menu.addSeparator()
        self.quit_action = QAction("退出", self)
        self.app_menu.addAction(self.quit_action)
        # File menu
        self.file_menu = self.menu_bar.addMenu("文件")
        self.open_mod_list_action = QAction("打开模组列表…", self)
        self.open_mod_list_action.setShortcut(QKeySequence("Ctrl+O"))
        self.file_menu.addAction(self.open_mod_list_action)
        self.file_menu.addSeparator()
        self.save_mod_list_action = QAction("另存为模组列表…", self)
        self.save_mod_list_action.setShortcut(QKeySequence("Ctrl+Shift+S"))
        self.file_menu.addAction(self.save_mod_list_action)
        self.file_menu.addSeparator()
        self.import_submenu = QMenu("导入")
        self.file_menu.addMenu(self.import_submenu)
        self.import_from_rentry_action = QAction("从 Rentry.co", self)
        self.import_submenu.addAction(self.import_from_rentry_action)
        self.import_from_workshop_collection_action = QAction(
            "从创意工坊集合", self
        )
        self.import_submenu.addAction(self.import_from_workshop_collection_action)
        self.file_menu.addSeparator()
        self.export_submenu = QMenu("导出")
        self.file_menu.addMenu(self.export_submenu)
        self.export_to_clipboard_action = QAction("到剪贴板…", self)
        self.export_submenu.addAction(self.export_to_clipboard_action)
        self.export_to_rentry_action = QAction("到 Rentry.co…", self)
        self.export_submenu.addAction(self.export_to_rentry_action)
        self.file_menu.addSeparator()
        self.upload_submenu = QMenu("上传日志")
        self.file_menu.addMenu(self.upload_submenu)
        self.upload_rimsort_log_action = QAction("RimSort.log", self)
        self.upload_submenu.addAction(self.upload_rimsort_log_action)
        self.upload_rimsort_old_log_action = QAction("RimSort.old.log", self)
        self.upload_submenu.addAction(self.upload_rimsort_old_log_action)
        self.upload_rimworld_log_action = QAction("RimWorld.log", self)
        self.upload_submenu.addAction(self.upload_rimworld_log_action)
        # Edit menu
        self.edit_menu = self.menu_bar.addMenu("编辑")
        self.cut_action = QAction("剪切", self)
        self.cut_action.setShortcut(QKeySequence("Ctrl+X"))
        self.edit_menu.addAction(self.cut_action)
        self.copy_action = QAction("复制", self)
        self.copy_action.setShortcut(QKeySequence("Ctrl+C"))
        self.edit_menu.addAction(self.copy_action)
        self.paste_action = QAction("粘贴", self)
        self.paste_action.setShortcut(QKeySequence("Ctrl+V"))
        self.edit_menu.addAction(self.paste_action)
        self.edit_menu.addSeparator()
        self.rule_editor_action = QAction("规则编辑器…", self)
        self.edit_menu.addAction(self.rule_editor_action)
        # Download menu
        self.download_menu = self.menu_bar.addMenu("下载")
        self.add_git_mod_action = QAction("添加 Git 模组", self)
        self.download_menu.addAction(self.add_git_mod_action)
        self.download_menu.addSeparator()
        self.browse_workshop_action = QAction("浏览创意工坊", self)
        self.download_menu.addAction(self.browse_workshop_action)
        self.update_workshop_mods_action = QAction("更新创意工坊模组", self)
        self.download_menu.addAction(self.update_workshop_mods_action)
        # Instances menu
        self.instances_menu = self.menu_bar.addMenu("实例")
        self.instances_submenu = QMenu('当前: "默认"')
        self.backup_instance_action = QAction("备份实例…", self)
        self.restore_instance_action = QAction("还原实例…", self)
        self.clone_instance_action = QAction("克隆实例…", self)
        self.create_instance_action = QAction("创建实例…", self)
        self.delete_instance_action = QAction("删除实例…", self)
        self.instances_menu.addMenu(self.instances_submenu)
        self.instances_menu.addSeparator()
        self.instances_menu.addAction(self.backup_instance_action)
        self.instances_menu.addAction(self.restore_instance_action)
        self.instances_menu.addSeparator()
        self.instances_menu.addAction(self.clone_instance_action)
        self.instances_menu.addAction(self.create_instance_action)
        self.instances_menu.addAction(self.delete_instance_action)
        # Textures menu
        self.texture_menu = self.menu_bar.addMenu("纹理/贴图")
        self.optimize_textures_action = QAction("优化纹理/贴图", self)
        self.texture_menu.addAction(self.optimize_textures_action)
        self.texture_menu.addSeparator()
        self.delete_dds_textures_action = QAction("删除已经优化的纹理/贴图", self)
        self.texture_menu.addAction(self.delete_dds_textures_action)
        # Help menu
        self.help_menu = self.menu_bar.addMenu("帮助")
        self.wiki_action = QAction("RimSort Wiki…", self)
        self.help_menu.addAction(self.wiki_action)
        self.help_menu.addSeparator()
        self.validate_steam_client_action = QAction("验证 Steam 客户端模组", self)
        self.help_menu.addAction(self.validate_steam_client_action)

    def _do_menu_bar_non_macos(self) -> None:
        # File menu
        self.file_menu = self.menu_bar.addMenu("文件")
        self.open_mod_list_action = QAction("打开模组列表…", self)
        self.open_mod_list_action.setShortcut(QKeySequence("Ctrl+O"))
        self.file_menu.addAction(self.open_mod_list_action)
        self.file_menu.addSeparator()
        self.save_mod_list_action = QAction("另存为模组列表…", self)
        self.save_mod_list_action.setShortcut(QKeySequence("Ctrl+Shift+S"))
        self.file_menu.addAction(self.save_mod_list_action)
        self.file_menu.addSeparator()
        self.import_submenu = QMenu("导入")
        self.file_menu.addMenu(self.import_submenu)
        self.import_from_rentry_action = QAction("从 Rentry.co", self)
        self.import_submenu.addAction(self.import_from_rentry_action)
        self.import_from_workshop_collection_action = QAction(
            "从创意工坊集合", self
        )
        self.import_submenu.addAction(self.import_from_workshop_collection_action)
        self.file_menu.addSeparator()
        self.export_submenu = QMenu("导出")
        self.file_menu.addMenu(self.export_submenu)
        self.export_to_clipboard_action = QAction("到剪贴板…", self)
        self.export_submenu.addAction(self.export_to_clipboard_action)
        self.export_to_rentry_action = QAction("到 Rentry.co…", self)
        self.export_submenu.addAction(self.export_to_rentry_action)
        self.file_menu.addSeparator()
        self.upload_submenu = QMenu("上传日志")
        self.file_menu.addMenu(self.upload_submenu)
        self.upload_rimsort_log_action = QAction("RimSort.log", self)
        self.upload_submenu.addAction(self.upload_rimsort_log_action)
        self.upload_rimsort_old_log_action = QAction("RimSort.old.log", self)
        self.upload_submenu.addAction(self.upload_rimsort_old_log_action)
        self.upload_rimworld_log_action = QAction("RimWorld Player.log", self)
        self.upload_submenu.addAction(self.upload_rimworld_log_action)
        self.file_menu.addSeparator()
        self.settings_action = QAction("设置…", self)
        self.settings_action.setShortcut(QKeySequence("Ctrl+,"))
        self.file_menu.addAction(self.settings_action)
        self.file_menu.addSeparator()
        self.quit_action = QAction("退出", self)
        self.quit_action.setShortcut(QKeySequence("Ctrl+Q"))
        self.file_menu.addAction(self.quit_action)
        # Edit menu
        self.edit_menu = self.menu_bar.addMenu("Edit")
        self.cut_action = QAction("剪切", self)
        self.cut_action.setShortcut(QKeySequence("Ctrl+X"))
        self.edit_menu.addAction(self.cut_action)
        self.copy_action = QAction("复制", self)
        self.copy_action.setShortcut(QKeySequence("Ctrl+C"))
        self.edit_menu.addAction(self.copy_action)
        self.paste_action = QAction("粘贴", self)
        self.paste_action.setShortcut(QKeySequence("Ctrl+V"))
        self.edit_menu.addAction(self.paste_action)
        self.edit_menu.addSeparator()
        self.rule_editor_action = QAction("规则编辑器…", self)
        self.edit_menu.addAction(self.rule_editor_action)
        # Download menu
        self.file_menu = self.menu_bar.addMenu("下载")
        self.add_git_mod_action = QAction("添加 Git 模组…", self)
        self.file_menu.addAction(self.add_git_mod_action)
        self.file_menu.addSeparator()
        self.browse_workshop_action = QAction("浏览创意工坊", self)
        self.file_menu.addAction(self.browse_workshop_action)
        self.update_workshop_mods_action = QAction("更新创意工坊模组", self)
        self.file_menu.addAction(self.update_workshop_mods_action)
        # Instances menu
        self.instances_menu = self.menu_bar.addMenu("实例")
        self.instances_submenu = QMenu('当前: "实例"')
        self.backup_instance_action = QAction("备份实例…", self)
        self.restore_instance_action = QAction("还原实例…", self)
        self.clone_instance_action = QAction("克隆实例…", self)
        self.create_instance_action = QAction("创建实例…", self)
        self.delete_instance_action = QAction("删除实例…", self)
        self.instances_menu.addMenu(self.instances_submenu)
        self.instances_menu.addSeparator()
        self.instances_menu.addAction(self.backup_instance_action)
        self.instances_menu.addAction(self.restore_instance_action)
        self.instances_menu.addSeparator()
        self.instances_menu.addAction(self.clone_instance_action)
        self.instances_menu.addAction(self.create_instance_action)
        self.instances_menu.addAction(self.delete_instance_action)
        # Textures menu
        self.file_menu = self.menu_bar.addMenu("纹理/贴图")
        self.optimize_textures_action = QAction("优化纹理/贴图", self)
        self.file_menu.addAction(self.optimize_textures_action)
        self.file_menu.addSeparator()
        self.delete_dds_textures_action = QAction("删除.dds纹理/贴图", self)
        self.file_menu.addAction(self.delete_dds_textures_action)
        # Help menu
        self.help_menu = self.menu_bar.addMenu("帮助")
        self.wiki_action = QAction("RimSort Wiki…", self)
        self.help_menu.addAction(self.wiki_action)
        self.help_menu.addSeparator()
        self.check_for_updates_action = QAction("检查更新…", self)
        self.help_menu.addAction(self.check_for_updates_action)
        self.check_for_updates_on_startup_action = QAction(
            "启动时检查更新", self
        )
        self.check_for_updates_on_startup_action.setCheckable(True)
        self.help_menu.addAction(self.check_for_updates_on_startup_action)
        self.help_menu.addSeparator()
        self.validate_steam_client_action = QAction("验证 Steam 客户端模组", self)
        self.help_menu.addAction(self.validate_steam_client_action)
